---
- name: common 
  hosts: observ
  become: true
  roles:
    - { role: common }
  tags:
    - loki
    - prometheus   
    - grafana     
    
- name: prometheus 
  hosts: observ
  become: true
  roles:
    - { role: prometheus }
  tags:
    - prometheus

- name: grafana
  hosts: observ
  become: true
  tags:
    - grafana
  roles:
    - { role: grafana }
    
- name: loki
  hosts: observ
  become: true
  tags:
    - loki
  roles:
    - { role: loki }